module.exports = {
  apps: [
    {
      name: "ShiristiRoy",
      script: "npm",
      args: "start",
      cwd: "/root/ShiristiRoy",
      env: {
        NODE_ENV: "production",
      },
    },
  ],
};